### ISSUE TITLE
Add support for MarkLogic JSON node constructors/tests

### ISSUE THREAD

**Issue by malteseduck** [ligasgr/intellij-xquery#123]
https://developer.marklogic.com/features/json

In MarkLogic 8 there are new JSON types that can be referenced in XQuery:

object node
array node
number node
boolean node
null node

As well as the corresponding constructors:

object-node {}
array-node {}
null-node {}
number-node {}
boolean-node {}

**Comment by ligasgr** [comment]
Merged.
