### ISSUE TITLE
Closes #125 - FindUsages does not show proper options dialog for other languages after installing XQuery Support plugin

### ISSUE THREAD

**Issue by rzarajczyk** [ligasgr/intellij-xquery#125]
After installing XQuery Support plugin, the "Find Usages" in IntelliJ IDEA (14.1.3) stopped working correctly - I mean it still works, but doesn't ask a question "Do you want to find usages of the base method?" if I try to look for usages of the method which overrides some other method.
![01-find-usages](https://cloud.githubusercontent.com/assets/4639652/7877724/02f3582c-05df-11e5-9ace-a32063eb62ed.png)
![02-no-usages-found-and-no-question-about-finding-method-from-super-class](https://cloud.githubusercontent.com/assets/4639652/7877725/02f5bd56-05df-11e5-823e-41a2c6621e30.png)

In the screens above the question "Do you want to find usages of the base method?" should be asked - but it's not. After uninstalling this plugin, in such situations the question is asked.

**Comment by ligasgr** [comment]
Hi Rafal,

Thanks for raising the issue. The behaviour (even though no one has noticed it in the last 2 years) is as you described it. I verified it and it behaves exactly the same in IntelliJ versions 12, 13 and 14.
I'll try to address it in the upcoming release.

Thanks,
Grzegorz
