### ISSUE TITLE
New API for Zorba 3.0

### ISSUE THREAD

**Issue by mserg32** [ligasgr/intellij-xquery#127]
There is new base package (io.zorba.api.xqj) in Zorba 3.0.

**Comment by ligasgr** [comment]
Hey,

I've noticed that some time ago and even attempted to prepare the update but for some reason I was getting a lot of issues during compilation of SWIG sources and a lot of SEGFAULTs when I started using libzorbaapi prepared like that.
I'll try to rebuild it all again soon and see how it goes.

**Comment by ligasgr** [comment]
I've managed to build the bindings and integration tests work fine. For some reason whenever I try to run anything that is not just about strings the program crashes. Please let me know if you find any issues with the fresh bindings.
