### ISSUE TITLE
Module file names don't allow hyphens

### ISSUE THREAD

**Issue by eurochriskelly** [ligasgr/intellij-xquery#130]
I would like to be able to name modules in standard xquery "train-case" format.

e.g. my-xquery-module.xqy
 
This is pretty normal in XQuery but is not supported by the plugin which tries to sanitize the filename into camel case for some reason.

It should either allow hyphenated names or explain in the error message why it is refusing to create the file. I had to look in the source code to find out what caused the warning message. 

(Really great plugin by the way!)

**Comment by ligasgr** [comment]
Hi,
Thanks for raising the issue.
The reason for not using hyphenated names was that IDEA in many places (internal IDEA engine code) does rely on names not containing any characters that are not alphanumeric.
I'll review if this is still the case and if not then the rules might get relaxed!

Thanks for using the plugin and letting me know how to improve it!

**Comment by ligasgr** [comment]
Hi
The new rules for function names are as below:
- has to start with either _ (underscore) or letter
- can contain letters, numbers, hyphens, underscores
Hope these rules make sense now
