### ISSUE TITLE
Double click in an XML attribute only selects one character

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#132]
If I have an XML fragment such as:

    <basic:json type="object"></basic:json>

Double clicking on `basic`, `json` and `type` select the word as expected, but double clicking on `object` (i.e. the string content within the attribute) only selects a single character, where it should select the word.

NOTE: Given something like:

   let $msg := "Hello World";

Double clicking inside that string selects the word as expected (i.e. `Hello` or `World` in this example).

**Comment by rhdunn** [comment]
The same thing happens for text nodes. For example:

    <p>Hello</p>

Double clicking `Hello` only selects a single character.

**Comment by ligasgr** [comment]
Double clicking as well as using ctrl-w (select word) relies on the elements in internal AST being represented as separate tokens. Currently all of the elements that you mentioned are all having each character treated as a separate token.
I'll consider changing the lexical analysis change to see if it's possible to merge/group them.
