### ISSUE TITLE
Incorrect error using ancestor::node in XPath

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#133]
Given the XPath:

    ($foo//bar/ancestor::node)[1]

the error message:

    '(' expected, got ')'

is displayed. This is incorrect, as the construct is valid. It looks like the syntax is trying to validate structures like `node()`.

**Comment by ligasgr** [comment]
is the ancestor::node here pointing to an /ancestor with an element with name 'node'?
Something like this?
``` xquery
let $foo := <x><node><bar></bar></node></x>
return ($foo//bar/ancestor::node)[1]
```
It shouldn't be treated as an error, I agree.

**Comment by rhdunn** [comment]
That is correct, yes.
