### ISSUE TITLE
IntelliJ version is old

### ISSUE THREAD

**Issue by eurochriskelly** [ligasgr/intellij-xquery#139]
Hi,

I've been using the plugin on php storm and it's supports syntax highlighting for xml as well as code folding. Today I installed IntelliJ ultimate and there are far fewer features. The version on intellij is 0.0.9. PhpStorm uses 2.2.1.

Is there a way to get the latest version on intellij?

**Comment by eurochriskelly** [comment]
I found more information. It seems my build is  IU-143-381. On this page you list the plugin as supporting versions unil IU-141. 

So I suppose my IntelliJ version is slightly newer than what this plugin supports. I will keep an eye on the page for a newer build.

**Comment by ligasgr** [comment]
There should be a new version of plugin that supports Idea 15.

**Comment by eurochriskelly** [comment]
I checked but it's not listed on the repo page yet and version 0.0.9 still shows up in IntelliJ. Does it normally take some time to get approved on the jetbrains repository ? Thanks again.
