### ISSUE TITLE
/x:y style constructs flag declared namespaces as unused

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#143]
Using the latest code:

    xquery version "3.0";
    declare namespace html = "http://www.w3.org/1999/xhtml";
    /html:p

Flags the namespace as unused. This is a case not covered in the fix for issue #135.

**Comment by rhdunn** [comment]
The same applies to `element(x:y)` constructs:

    xquery version "3.0";
    declare namespace html = "http://www.w3.org/1999/xhtml";
    let $x as element(html:p)? := ()
    return $x

**Comment by ligasgr** [comment]
Thanks for valuable feedback! I probably wouldn't have found those so quickly!
