### ISSUE TITLE
MarkLogic map: and other built-in functions flagged as errors.

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#145]
Using the latest code, given:

    xquery version "1.0-ml";
    map:map()

The `map:map` function is flagged with the error `Cannot resolve function 'map:map'`. This affects the following built-in function namespaces:

*  `map:` (https://docs.marklogic.com/map)
*  `sem:` (https://docs.marklogic.com/sem/semantics)
*  `temporal:` (https://docs.marklogic.com/temporal/temporal)

I have done a quick check of the other built-in namespaces (not checking every function, just one from each namespace), and they are being picked up correctly.

**Comment by ligasgr** [comment]
I've refreshed the list based on the [official MarkLogic 8 documentation](https://docs.marklogic.com/guide/xquery/namespaces#id_21104).
For some reason temporal is not on the list.

**Comment by rhdunn** [comment]
You are correct. The documentation for `temporal` says that you must import that module.
