### ISSUE TITLE
Explicitly specifying the extension of a new XQuery file flags the name as invalid.

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#149]
Creating a new XQuery file `foo` creates a new file according to the default extension. Explicitly specifying an extension with `foo.xqy` or `foo.xq` causes the name to be rejected as invalid. Those cases should be accepted as valid.

**Comment by ligasgr** [comment]
"New XQuery File" dialog never allowed specifying file extension.
I'll have a look if such a feature is doable using IntelliJ platform.

**Comment by ligasgr** [comment]
New file templates are new available for modification by users under Settings->Editor->File and Code templates->Files->XQuery Main Module/XQuery Library Module.
By default new module namespace prefix will be the name given in the dialog with extension (if provided) removed and the namespace will be the file name.
From now on the dot will be accepted as part of the file name.
