### ISSUE TITLE
A lone closing comment sequence `:)` after a MarkLogic transaction should be flagged as an error.

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#155]
Given

    :)
    ()
    ;
    :)
    ()

The first `:)` is flagged as an error, but the second `:)` is not. This is also reproducible without the first `:)` -- the key part is the MarkLogic transaction separator.

**Comment by ligasgr** [comment]
Please see https://github.com/ligasgr/intellij-xquery/issues/113
Semicolon is currently not supported as transaction separator.
