### ISSUE TITLE
XQuery 3.1 support

### ISSUE THREAD

**Issue by ligasgr** [ligasgr/intellij-xquery#156]
http://www.w3.org/TR/xquery-31/

**Comment by ligasgr** [comment]
http://exist-db.org/exist/apps/wiki/blogs/eXist/XQuery31
http://docs.basex.org/wiki/XQuery_3.1

**Comment by zyv** [comment]
Maybe this could be done in steps?

In particular, what I'm mostly missing right now, is the support for awesome new builtin functions, like

  * fn:sort
  * JSON functions
  * => (arrow operator)

This sounds like a relatively easy task as compared to revising the current implementation to add full support for XQ 3.1 specification, and would definitively be a quick win.
