### ISSUE TITLE
XPath constructs are not validated.

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#170]
Given:

    <p class="{$items[@id=$id}]">Test</p>
                             ^----- expected `]`, got `}`

the indicated error message (or equivalent) is not flagged. This should apply to all places where XPath statements can occur, and for all XPath errors.

**Comment by ligasgr** [comment]
Interestingly enough it works fine with:
``` xquery
<p class="{$items[@id=$id}]"/>
```
