### ISSUE TITLE
Missing $ in for construct not reported as an error.

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#176]
Given:

    let $a := (1, 2, 3)
    return for $b in a return $b
                     ^----- missing '$'

The `missing '$'` error or similar should be reported, but isn't.

**Comment by ligasgr** [comment]
hi,

This is perfectly, syntacticly valid code. 'a' in this case is 'step expression' with 'forward step' which simply means that this expression will take an element 'a' from context item.
Full path is StepExpr->AxisStep->ForwardStep->AbbrevForwardStep->NodeTest->NameTest.
More details here: https://www.w3.org/TR/xquery-30/#doc-xquery30-ForwardStep
