### ISSUE TITLE
'default' in a typeswitch statement within a function not highlighted when typing

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#177]
Given:

    declare function test($a) {
        typeswitch ($a)
            case document-node() return ()
            <caret>
    };
    ()

with the cursor at `<caret>`, typing:

    default return ()

causes the `default` keyword to be highlighted as an identifier, not as a keyword.

The `default` keyword is correctly highlighted in this context when (a) pasting the `default` line, (b) writing the typeswitch statement outside the function.

**Comment by ligasgr** [comment]
Fixed in #178
