### ISSUE TITLE
'catch' is not highlighted as a keyword in ML8 XQuery

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#178]
Given:

    try {
        ()
    } catch ($ex) {
        ()
    }

the `catch` statement is highlighted as an identifier, not as a keyword.

**Comment by ligasgr** [comment]
Just to add more context: it only happens when typing in everything by hand. When pasted or re-opened - works fine. Related to YYINITIAL state and re-lexing/re-parsing.
