### ISSUE TITLE
'declare function' not being syntax highlighted when editing a function above it

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#181]
Given:

    declare function test1($a) {
        <a>
           <b type="test">hello</b>
        </a>
    };

    declare function test2() {
        ()
    };

    ()

In the `type="test"` attribute:

1.  change the `test` content to `{}`
2.  between the braces, enter `"` then `"` (so `test` is now `{""}`)

After (2), `declare function` is now highlighted as identifiers, not keywords.

NOTE: This is in usage such as:

    <b type="{if ($a) then "one" else "two"}">

Some other observations:

1.  Removing the outer `<a>` elements and repeating the tests do not exhibit the above behaviour.
2.  Removing the parameters in `test1` (i.e. `declare function test1()`) and repeating the tests do not exhibit the above behaviour.

**Comment by ligasgr** [comment]
Should be fixed by https://github.com/ligasgr/intellij-xquery/issues/178
