### ISSUE TITLE
typing 'default' in a typeswitch statement incorrectly highlights default

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#182]
Typing:

    typeswitch ($a)
        case document-node() return ()
        default return ()

results in the `default` token not being identified as a keyword, whereas `case` is. Note that pasting the above example in results in the correct behaviour.

**Comment by ligasgr** [comment]
Is this not a duplicate of https://github.com/ligasgr/intellij-xquery/issues/177 ?

**Comment by rhdunn** [comment]
Yes, sorry. I get confused as to which bugs I have raised :).

**Comment by ligasgr** [comment]
No problem :)
Thanks for raising them. I would not be able to find all of those edge cases myself!
