### ISSUE TITLE
XML element not highlighted when entering an element node before `()`

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#183]
Given:

```
()
```

Typing `<test` before the `()` to give:

```
<test
()
```

the `test` identifier is not highlighted as an XML element (i.e. maroon). Closing the tag causes a correctly highlighted element to be inserted.

This does not happen given `return ()` to start with, but occurs when incrementally editing an XQuery file. The context I am encountering this is with constructs like `let $a := <test` -- the above steps to reproduce are just the minimal steps to re-create the behaviour.

**Comment by rhdunn** [comment]
This also happens with comments -- e.g. `(: foo :)` -- as well as `()`.

**Comment by ligasgr** [comment]
Will be fixed as part of #9 .
