### ISSUE TITLE
The plugin doesn't work with the newly released Intellij IDEA 2016.1

### ISSUE THREAD

**Issue by itoshkov** [ligasgr/intellij-xquery#189]
The plugin is not compatible with the newly released Intellij IDEA 2016.1.

**Comment by satinfield** [comment]
please fix this

**Comment by cefn** [comment]
Yes please. I am happy to test it, if it's just a matter of changing the version information and trying it out. However, perhaps @ligasgr can tell us if there is actually an incompatiblity, or if it's just a version number which needs to be bumped.

**Comment by cefn** [comment]
OK, I bumped the 'until' version to 145.999 within /intellij-xquery/lib//intellij-xquery.jar in the file called /META-INF/plugin.xml and I have successfully completed installation with the resulting zip and have syntax highlighting for XQuery files on 145.258 . Haven't tested further than this, though.

**Comment by itoshkov** [comment]
Thanks! It works for me, though I don't really use the embedded saxon, so I didn't test many of the features.
