### ISSUE TITLE
Can't select certain main module files (.xquery)

### ISSUE THREAD

**Issue by gsf-greece** [ligasgr/intellij-xquery#195]
I've noticed this bug some time ago but I always work around it. I know when you create a new Run configuration you can select only main modules and not library modules. However, I have some main modules that can't be selected for some reason.

I've tried changing the file name, deleting parts of the content, but I can't really locate why this happens.
even when I only leave this script 
`xquery version "3.1" encoding "UTF-8";
1
`
It doesn't make a difference most of the times. It only randomly starts working after a while.

**Comment by ligasgr** [comment]
Can you please first of all clarify what you mean by "can't be selected"? Does it mean that you can't run it? Or does not allow for "auto-generation" of run config (e.g. pressing ctrl-shift-f10)?

Can you please share the screenshots of the right-click menu in the contents of the file when it doesn't work? Also screenshot of the list of 'Run selectbox' in the menu bar would be helpful from the moment when it doesn't work. Please also let me know if there are any errors in the ["gutter"](https://confluence.jetbrains.com/display/PYH/Syntax+highlighting+and+error+indication#Syntaxhighlightinganderrorindication-Errorindication) area on files that don't allow "selection".
Please let me know if creation of the new run configuration for the file manually (Run -> Edit configurations -> "+" button (Add New Configuration) -> XQuery Main Module) works fine (e.g. lets you do that and actually run it)?

**Comment by gsf-greece** [comment]
OK sorry for being vague. I had no idea you can create a new configuration by right clicking at the content of the file. I was just trying to manually create a new run configuration. I only have trouble selecting the main module at the screen of the manual run configuration. If I right click in the context of the main module and I select Create filename, it works.
I'm uploading a screenshot, I hope this helps

![forligas](https://cloud.githubusercontent.com/assets/6191600/15793767/eb56d2fe-29ee-11e6-9b0b-dd96af4f397e.PNG)

**Comment by ligasgr** [comment]
Can you please try with the latest version (released yesterday)? I did some changes to use the new API for running.

**Comment by gsf-greece** [comment]
Unfortunately it still isn't working. Here is the file I'm trying to use https://my.pcloud.com/publink/show?code=XZTBPbZVhoPP14rCym1hcUvCqVtshxU2K7k

**Comment by ligasgr** [comment]
I understand that the issue only happens when you try to create manually and you are not able to select files on the list of files. I'm fixing that issue. If there's any other problem related to this functionality, please raise a new issue.

**Comment by ligasgr** [comment]
If you'd like to get the latest build of the plugin you should be able to build it yourself by following [collaboration page](http://ligasgr.github.io/intellij-xquery/collaboration.html#building-plugin-locally) and the running
```gradlew.bat dist```
The built zip file should be in build/distributions. You can use this file to [install plugin from disk](https://www.jetbrains.com/help/idea/2016.1/installing-plugin-from-disk.html).
If this doesn't work just let me know and I can prepare the zip for you.
