### ISSUE TITLE
Map as a global variable

### ISSUE THREAD

**Issue by gsf-greece** [ligasgr/intellij-xquery#197]
I was trying to set a map as a global variable, but I get a parsing error about using **:** in the first key. 
For example declare variable $TEST as map(*) := map { 1: 2, 3: 4 }

I was using the BaseX flavour if that makes any difference

**Comment by ligasgr** [comment]
Hey
This is a duplicate of #166 and #156. Current map syntax is based on early implementation of maps in Saxon.
