### ISSUE TITLE
Cannot resolve imported module variables/functions

### ISSUE THREAD

**Issue by millerbill3** [ligasgr/intellij-xquery#203]
First of all, I love this plugin!
Question... in my xquery modules/files where I'm referencing an imported module's variables/functions I'm getting a "cannot resolve variable ...".
I'm using MarkLogic 8 as my database and IntelliJ Ultimate 2016.1.
I have configured the plugin with the appropriate login information and I'm pointing to a WebDav database. Is this correct?
I have also tried configuring the plugin to connect to one of my HTTP servers, but still have the same issue.
Thanks...

**Comment by ligasgr** [comment]
Hey,

Thanks for kind words :) 👍 
Can you please show a screenshot of which modules/variables are getting "cannot resolve variable"? Just a few examples.
Also, can you please let me know if the sources of those imported modules are part of the project? Are they part of standard MarkLogic API (e.g. available in https://docs.marklogic.com/ )?
Currently plugin does not support fetching/browsing modules in WebDav. Please raise a separate issue with the description of the expected functionality if you'd be interested in such feature.
What you have configured is a data source used for running XQuery code (for MarkLogic it generally works only when all of the used [imported] modules are either standard api or uploaded to server). It requires adding XDBC server and specifying its port in the data source configuration.
Can you please also let me know what you have selected in File -> Settings -> Other settings -> XQuery -> Other options -> XQuery flavour?

**Comment by millerbill3** [comment]
Hi and thanks for the quick response.
As for my settings I have MarkLogic 8 selected as the XQuery flavor.
In my XQuery Data Sources, I have the following settings:

   - Name: MarkLogic-local
   - Host: localhost
   - Port: 8041 (references XDBC connection)
   - Database name: sof-sdl-modules (references Modules/Content databases
   for my project where code/modules for project reside)
   - Username: login user name
   - Password: Password for DB
   - NOTE: The XDBC server is set up to use Digest authentication

Here is an example of the plugin not seeing imported module
methods/variables
[image: Screen Shot 2016-07-18 at 7.57.22 AM.png]
Module imports above.
Then, further down in the same module...
[image: Screen Shot 2016-07-18 at 7.58.12 AM.png]
Here you can see the imported modules for "req", "status-lib", "cp", etc
being imported and then later on where they are referenced you can see the
plugin highlighting them in red with "mouse-over" hints stating "Cannot
resolve variable XXX".

Thanks,
Bill

**Comment by ligasgr** [comment]
Hey,

Thanks for more details.
Unfortunately you'd have to respond on github portal and not via email for attachments to be visible to me.

**Comment by millerbill3** [comment]
Sorry,
Didn't realize the images would not be visible in the email.
![screen shot 2016-07-19 at 7 22 40 am](https://cloud.githubusercontent.com/assets/6152078/16948247/a2413026-4d81-11e6-8816-b9a487c2ce84.png)
![screen shot 2016-07-18 at 7 58 12 am](https://cloud.githubusercontent.com/assets/6152078/16948251/aaadc580-4d81-11e6-8ad9-fc116c79e918.png)

**Comment by ligasgr** [comment]
Hey,

please raise a separate issue for WebDav module access for MarkLogic.
This would be to allow browsing the modules currently deployed onto the server and allow referencing them in the code in the IDE.
Current functionality does not allow that. To get rid of these warnings you could copy the modules that get these highlights into the workspace into one of the source directories.
I know that it's not ideal but currently that is the only way.

**Comment by millerbill3** [comment]
Ok, thanks
