### ISSUE TITLE
Support for community edition

### ISSUE THREAD

**Issue by gjwilson21** [ligasgr/intellij-xquery#205]
Hi, 

Just wanted to check, does this plugin work for the community edition? Also, are there any documentation to get started with creating an xquery project, etc?

Thanks
Joel

**Comment by ligasgr** [comment]
Hi,
This plugin does work with all IntelliJ platform based products except for MPS.
There is unfortunately no beginner documentation.
There is no special project type to create when you want to use XQuery as the language is usually integrated into base language projects (e.g. java/python/etc).
Please contact me via email if you need further details.
