### ISSUE TITLE
Plugin is incompatible with the latest version

### ISSUE THREAD

**Issue by lagivan** [ligasgr/intellij-xquery#206]
The plugin has stopped working after the last upgrade. It does not appear in "Browse repositories" dialog and using "Install plugin from disk" returns the following error message:

Plugin 'XQuery Support' is incompatible with this installation

IntelliJ IDEA 2016.3
Build #IU-163.7743.44, built on November 18, 2016

**Comment by ligasgr** [comment]
Closed by #207
