### ISSUE TITLE
Update plugin to support IntelliJ 17.1

### ISSUE THREAD

**Issue by w17chm4n** [ligasgr/intellij-xquery#211]
A new year - a new IntelliJ :wink:

**Comment by millerbill3** [comment]
How long before the IntelliJ 17.1 support commit is available via the IntelliJ Plugin manager?

**Comment by millerbill3** [comment]
Has this update been merged yet? Really need to get this installed ASAP.
Thanks!

**Comment by w17chm4n** [comment]
No it hasn't. If you need it then recompile it yourself. It's not that complicated and tbh - it's what I did.

**Comment by w17chm4n** [comment]
You shouldn't care about IntelliJ complaining about unindexed repositories. Just follow the steps in [collaboration](http://ligasgr.github.io/intellij-xquery/collaboration.html). The only thing You need to do is to edit `build.gradle` and edit `project.ext.userDefinedInstallationPath`. Then apply the patch that @lagivan provided in his fork and built the plugin itself.

**Comment by ligasgr** [comment]
Hey
Sorry for late response on this one. Will release it today.
Thanks for raising and to @lagivan for contributing the patch!

**Comment by millerbill3** [comment]
Got the update today. Thanks!!!
