### ISSUE TITLE
Find usages should not show usages in text files

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#226]
Given:

    declare function test($path as xs:string) {
        let $x := if (fn:empty($path)) then 1 else 2
        return $x
    };

Clicking on the `test`, `path`, `x` and `empty` NCNames return matches from unrelated files, such as markdown documentation and ruby files (e.g. `framework.rb` from MarkLogic Roxy). This is with version 3.3.0 of the plugin.

**Comment by ligasgr** [comment]
This has been the default behaviour of find usages since the very beginning of the plugin (which made sense at that time as the referencing logic did not work for most of the cases).
It makes sense to disable searching in text files and hence I'm making that change.
